// <auto-generated />
using System;
using Concretera.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Concretera.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429005928_AddConductorFields")]
    partial class AddConductorFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Concretera.Core.Models.Camion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CapacidadM3")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CargaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CargaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConductorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DescargaFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("DescargaMinutos")
                        .HasColumnType("int");

                    b.Property<string>("DestinoDireccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DestinoLat")
                        .HasColumnType("float");

                    b.Property<double?>("DestinoLng")
                        .HasColumnType("float");

                    b.Property<string>("DestinoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LlegadaEstimada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placas")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("RegresoFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelMinutos")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.ToTable("Camiones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacidadM3 = 7.0,
                            Color = "#f0a030",
                            DescargaMinutos = 15,
                            Nombre = "Camión 1",
                            Placas = "ABC-001",
                            Status = "LIBRE",
                            TravelMinutos = 0,
                            UltimaActualizacion = new DateTime(2026, 4, 29, 0, 59, 27, 957, DateTimeKind.Utc).AddTicks(6405)
                        },
                        new
                        {
                            Id = 2,
                            CapacidadM3 = 7.0,
                            Color = "#e05599",
                            DescargaMinutos = 15,
                            Nombre = "Camión 2",
                            Placas = "ABC-002",
                            Status = "LIBRE",
                            TravelMinutos = 0,
                            UltimaActualizacion = new DateTime(2026, 4, 29, 0, 59, 27, 957, DateTimeKind.Utc).AddTicks(7492)
                        },
                        new
                        {
                            Id = 3,
                            CapacidadM3 = 7.0,
                            Color = "#4b9ef5",
                            DescargaMinutos = 15,
                            Nombre = "Camión 3",
                            Placas = "ABC-003",
                            Status = "LIBRE",
                            TravelMinutos = 0,
                            UltimaActualizacion = new DateTime(2026, 4, 29, 0, 59, 27, 957, DateTimeKind.Utc).AddTicks(7496)
                        },
                        new
                        {
                            Id = 4,
                            CapacidadM3 = 7.0,
                            Color = "#4caf7d",
                            DescargaMinutos = 15,
                            Nombre = "Camión 4",
                            Placas = "ABC-004",
                            Status = "LIBRE",
                            TravelMinutos = 0,
                            UltimaActualizacion = new DateTime(2026, 4, 29, 0, 59, 27, 957, DateTimeKind.Utc).AddTicks(7497)
                        },
                        new
                        {
                            Id = 5,
                            CapacidadM3 = 7.0,
                            Color = "#e05555",
                            DescargaMinutos = 15,
                            Nombre = "Camión 5",
                            Placas = "ABC-005",
                            Status = "LIBRE",
                            TravelMinutos = 0,
                            UltimaActualizacion = new DateTime(2026, 4, 29, 0, 59, 27, 957, DateTimeKind.Utc).AddTicks(7498)
                        },
                        new
                        {
                            Id = 6,
                            CapacidadM3 = 7.0,
                            Color = "#9b72f5",
                            DescargaMinutos = 15,
                            Nombre = "Camión 6",
                            Placas = "ABC-006",
                            Status = "LIBRE",
                            TravelMinutos = 0,
                            UltimaActualizacion = new DateTime(2026, 4, 29, 0, 59, 27, 957, DateTimeKind.Utc).AddTicks(7499)
                        });
                });

            modelBuilder.Entity("Concretera.Core.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ContactoObra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelefonoObra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelMinutosDefault")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Concretera.Core.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CamionId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("DescargaMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAsignada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitada")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaDigitalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoEntregaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<double>("M3Solicitados")
                        .HasColumnType("float");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TravelMinutos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CamionId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Concretera.Core.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("CamionAsignadoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LicenciaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroLicencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CamionAsignadoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@concretera.com",
                            FechaIngreso = new DateTime(2026, 4, 29, 0, 59, 27, 958, DateTimeKind.Utc).AddTicks(3104),
                            Nombre = "Administrador",
                            PasswordHash = "$2a$11$Ra2gzyPttvSDpP7GgLOf2eFKAIzpaUJCgbiupq9bYwJ81cnLIrCv2",
                            Rol = "ADMIN"
                        });
                });

            modelBuilder.Entity("Concretera.Core.Models.Viaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CamionId")
                        .HasColumnType("int");

                    b.Property<int>("CargaMinutos")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("ConductorId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoCombustible")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DescargaMinutos")
                        .HasColumnType("int");

                    b.Property<string>("DireccionDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistanciaKm")
                        .HasColumnType("float");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaDigitalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoEntregaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ingresos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<double>("M3Entregados")
                        .HasColumnType("float");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("TarifaM3")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TiempoTotalMinutos")
                        .HasColumnType("int");

                    b.Property<int>("TravelMinutosIda")
                        .HasColumnType("int");

                    b.Property<int>("TravelMinutosVuelta")
                        .HasColumnType("int");

                    b.Property<decimal>("Utilidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CamionId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ConductorId");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("Viajes");
                });

            modelBuilder.Entity("Concretera.Core.Models.Camion", b =>
                {
                    b.HasOne("Concretera.Core.Models.Usuario", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Conductor");
                });

            modelBuilder.Entity("Concretera.Core.Models.Pedido", b =>
                {
                    b.HasOne("Concretera.Core.Models.Camion", "Camion")
                        .WithMany()
                        .HasForeignKey("CamionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Concretera.Core.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camion");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Concretera.Core.Models.Usuario", b =>
                {
                    b.HasOne("Concretera.Core.Models.Camion", "CamionAsignado")
                        .WithMany()
                        .HasForeignKey("CamionAsignadoId");

                    b.Navigation("CamionAsignado");
                });

            modelBuilder.Entity("Concretera.Core.Models.Viaje", b =>
                {
                    b.HasOne("Concretera.Core.Models.Camion", "Camion")
                        .WithMany("Viajes")
                        .HasForeignKey("CamionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Concretera.Core.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concretera.Core.Models.Usuario", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Concretera.Core.Models.Pedido", "Pedido")
                        .WithOne("Viaje")
                        .HasForeignKey("Concretera.Core.Models.Viaje", "PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camion");

                    b.Navigation("Cliente");

                    b.Navigation("Conductor");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Concretera.Core.Models.Camion", b =>
                {
                    b.Navigation("Viajes");
                });

            modelBuilder.Entity("Concretera.Core.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Concretera.Core.Models.Pedido", b =>
                {
                    b.Navigation("Viaje");
                });
#pragma warning restore 612, 618
        }
    }
}
